### ISSUE TITLE
Failed to run wit

### ISSUE THREAD

**Issue by benbrandt** [valentinegb/zed-wit#2]
zed  keeps saying it "failed to run wit" with the following error

```
Language server error: wit

wit-cli must be installed and available on your $PATH
-- stderr--

```

**Comment by valentinegb** [comment]
You must install `wit-cli` with Cargo (which you must also install if you haven't already) using this command if you wish to enable LSP features:

```sh
cargo install --git https://github.com/Michael-F-Bryan/wit-lsp.git wit-cli
```

**Comment by valentinegb** [comment]
I'll add some instructions to the README when I get the chance, since this is understandable

**Comment by benbrandt** [comment]
I took a first pass in case it is helpful. Thanks!
